PL_MVC/Controllers/AseguradoraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class AseguradoraController : Controller
    {
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Result result = BL.Aseguradora.GetAllEF();

            if (result.Correct)
            {
                ML.Aseguradora aseguradora = new ML.Aseguradora();
                aseguradora.Aseguradoras = result.Objects;

                return View(aseguradora);
            }
            else
            {
                ViewBag.Message = $"Error: {result.ErrorMessage}";
            }
            return View();
        }

        [HttpGet]
        public ActionResult Form(int? IdAseguradora)
        {
            ML.Aseguradora aseguradora = new ML.Aseguradora();
            ML.Result resultUsuarios = BL.Usuario.GetAllEF(new ML.Usuario());

            if (IdAseguradora == null)
            {
                //Formulario vacio pal ADD
                aseguradora.Usuario = new ML.Usuario();
            }
            else
            {
                //Formulario lleno por GetByID
                ML.Result result = BL.Aseguradora.GetByIdEF(IdAseguradora.Value);

                if (result.Correct)
                {
                    aseguradora = (ML.Aseguradora)result.Object;
                }
                else
                {
                    ViewBag.Message = $"Error: {result.ErrorMessage}";
                }
            }

            foreach (ML.Usuario usuario in resultUsuarios.Objects)
            {
                usuario.Nombre = $"{usuario.Nombre} {usuario.ApellidoPaterno} {usuario.ApellidoMaterno}";
                //usuario.Nombre = usuario.Nombre + usuario.ApellidoPaterno + usuario.ApellidoMaterno;
            }
            aseguradora.Usuario.Usuarios = resultUsuarios.Objects;

            return View(aseguradora);
        }

        [HttpPost]
        public ActionResult Form(ML.Aseguradora aseguradora)
        {
            if (aseguradora.IdAseguradora == 0)
            {
                ML.Result result = BL.Aseguradora.AddEF(aseguradora);
                if (result.Correct)
                {
                    ViewBag.Message = "Aseguradora agregada con éxito.";
                }
                else
                {
                    ViewBag.Message = $"Error: {result.ErrorMessage}";
                }
            }
            else
            {
                //Update
                ML.Result result = BL.Aseguradora.UpdateEF(aseguradora);
                if (result.Correct)
                {
                    ViewBag.Message = "Aseguradora modificada con éxito.";
                }
                else
                {
                    ViewBag.Message = $"Error: {result.ErrorMessage}";
                }
            }
            return PartialView("Modal");
        }

        [HttpGet]
        public ActionResult Delete(int? IdAseguradora)
        {
            if (IdAseguradora == null)
            {
                ViewBag.Message = "Error al intentar encontrar al usuario.";
            }
            else
            {
                ML.Result result = BL.Aseguradora.DeleteEF(IdAseguradora.Value);

                if (result.Correct)
                {
                    ViewBag.Message = "Aseguradora eliminada con éxito.";
                }
                else
                {
                    ViewBag.Message = $"Error: {result.ErrorMessage}";
                }
            }
            return PartialView("Modal");
        }
    }
}

PL_MVC/Views/Aseguradora/Form.cshtml
@model ML.Aseguradora
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Form</h2>

    <div class="row">

        <div class="col-md-12">

            @using (Html.BeginForm("Form", "Aseguradora", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-horizontal">
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(Model => Model.IdAseguradora, new { @class = "hidden form-control" })
                            @Html.TextBoxFor(Model => Model.IdAseguradora, new { @class = "form-control hidden form-control" })
                            @Html.ValidationMessageFor(Model => Model.IdAseguradora)
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(Model => Model.Nombre)
                            @Html.TextBoxFor(Model => Model.Nombre, new { @class = "form-control", @id = "txtNombre" })
                            @Html.ValidationMessageFor(Model => Model.Nombre)
                        </div>
                    </div>

                    @*<div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(Model => Model.FechaCreacion)
                            @Html.TextBoxFor(Model => Model.FechaCreacion, new { @class = "form-control", @id = "txtNombre" })
                            @Html.ValidationMessageFor(Model => Model.FechaCreacion)
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(Model => Model.FechaModificacion)
                            @Html.TextBoxFor(Model => Model.FechaModificacion, new { @class = "form-control", @id = "txtNombre" })
                            @Html.ValidationMessageFor(Model => Model.FechaModificacion)
                        </div>
                    </div>*@

                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(Model => Model.Usuario.IdUsuario)
                            @*@Html.TextBoxFor(Model => Model.Rol.IdRol, new { @class = "form-control", @id = "txtNombre" })*@
                            @Html.DropDownListFor(model => model.Usuario.IdUsuario, new SelectList(Model.Usuario.Usuarios, "IdUsuario", "Nombre"), "Selecciona una opción", new { @class = "form-control" })
                            @Html.ValidationMessageFor(Model => Model.Usuario.IdUsuario)
                        </div>
                    </div>
                    <div class="form-group">

                        <div class="col-md-3">

                            <input type="submit" value="Guardar" class="btn btn-success" />
                            @Html.ActionLink("Regresar", "GetAll", "Aseguradora", htmlAttributes: new { @class = "btn btn-danger" })

                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

PL_MVC/Views/Aseguradora/GetAll.cshtml
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model ML.Aseguradora

<div class="container">

    <h2>Aseguradoras</h2>

    <p>Bienvenidos a la pestaña Aseguradora</p>

    <div class="row">
        <div style="float:right">
            @Html.ActionLink("+", "Form", "Aseguradora", htmlAttributes: new { @class = "btn btn-success" })
        </div>
    </div>

    <hr />

    <div class="row">

        <table class="table table-responsive table-hover">

            <thead class="table table-dark">
                <tr>
                    <th>Editar</th>
                    @*<th>ID</th>*@
                    <th>Nombre</th>
                    <th>Fecha de creación</th>
                    <th>Fecha de modificación</th>
                    <th>Usuario</th>
                    <th>Eliminar</th>
                </tr>
            </thead>

            <tbody>

                @foreach (ML.Aseguradora aseguradora in Model.Aseguradoras)
                {
                    <tr>
                        <td class="text-center"><a class="btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("Form", "Aseguradora", new {IdAseguradora = aseguradora.IdAseguradora})"></a></td>
                        @*<td>@aseguradora.IdAseguradora</td>*@
                        <td>@aseguradora.Nombre</td>
                        <td>@aseguradora.FechaCreacion</td>
                        <td>@aseguradora.FechaModificacion</td>
                        <td>@aseguradora.Usuario.Nombre @aseguradora.Usuario.ApellidoPaterno @aseguradora.Usuario.ApellidoMaterno</td>
                        <td class="text-center"><a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "Aseguradora", new {IdAseguradora = aseguradora.IdAseguradora})" onclick="return confirm('¿Estás seguro que deseas eliminar la aseguradora?');"></a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

PL_MVC/Views/Aseguradora/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Aceptar", "GetAll", "Aseguradora", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>